# WARNING: This file is automatically managed by puppet. You should not customize settings here.
# @todo Come up with a way for users to customize settings during development

import os
from ConfigParser import RawConfigParser

# Import the developer settings
from settings_dev import *

config_ini = RawConfigParser()
config_ini.read('/var/lib/gareth/config/db.ini')

# Use a secret key stored in config (generated by puppet)
with open('/var/lib/gareth/config/secret_key') as f:
	SECRET_KEY = f.read().strip()

# Configure the repository path
REPO_PATH = '/var/lib/gareth/repos'

# Setup the database
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': config_ini.get('db', 'name'),
		'USER': config_ini.get('db', 'user'),
		'PASSWORD': config_ini.get('db', 'pass'),
		'HOST': '',
		'PORT': '',
	}
}

# Setup the message queue system
STOMP = {
	'host': ('localhost', 61613),
	'user': 'admin',
	'pass': 'vagrant',
	'version': 1.1,
}
